### ISSUE TITLE
v0.6/LinkToken uses the 0.7.x compiler version instead of 0.6.x

### ISSUE THREAD

**Issue by yosriady** [smartcontractkit/LinkToken#45]
When compiling the contracts, the v0.6/LinkToken contracts are compiled using `0.7.6` instead of `0.6.12` which does not match what is configured in the Hardhat [config](https://github.com/smartcontractkit/LinkToken/blob/master/hardhat.config.ts):

```
const versions: Record<string, SolcConfig> = {
  'v0.4': { version: '0.4.16', settings },
  'v0.6': { version: '0.6.12', settings },
  'v0.7': { version: '0.7.6', settings },
}
```

## How to Reproduce

Run `yarn build:contracts/v0.6` and inspect the ABIs in `build/`.

**Comment by krebernisak** [comment]
Here is a commit that fixes this: https://github.com/smartcontractkit/LinkToken/pull/33/commits/9e0dcd8bbf2d2812ea17187b9307cd55a31d34cc5

Please note that if just the `yarn build` cmd is used, then the resulting artifacts will be compiled with the compiler the build process ended with (latest version). So if a specific compiler is required, one needs to use specific cmds like `yarn build:contracts/v0.6`. I'll add a notice in the README.

**Comment by yosriady** [comment]
Do you mean `yarn setup`? Compilation on that branch doesn't seem to work for me.

How do you generate the 0.7.6 ABI? I tried both:

```
yarn setup
```

and

```
yarn build:contracts:0.6
```

but they both error out:

```
Error HH404: File ../../vendor/OpenZeppelin/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol, imported from contracts/v0.6/ERC677.sol, not found.
```

**Comment by krebernisak** [comment]
The error @yosriady had was because the submodules were not pulled with `git submodule update --init --recursive`.

Closing this issue as it was fixed in https://github.com/smartcontractkit/LinkToken/pull/33
