### ISSUE TITLE
ParserError: Expected identifier but got reserved keyword 'immutable'     LinkTokenInterface internal immutable LINK;

### ISSUE THREAD

**Issue by JBush511** [smartcontractkit/LinkToken#53]
When I compile or when i attempt to deploy the code, I get the same error. I've restarted the lesson all over again to make sure I didn't miss anything and I eventually got to this same error again, when I enter 'brownie compile' or 'brownie run scripts/deploy_lottery.py' . my error code shows:

'Brownie v1.16.4 - Python development framework for Ethereum

Compiling contracts...
Solc version: 0.6.0
Optimizer: Enabled Runs: 200
EVM Version: Istanbul
CompilerError: solc returned the following errors:

/Users/mrandmrsbush/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/VRFConsumerBase.sol:186:33: ParserError: Expected identifier but got reserved keyword 'immutable'
LinkTokenInterface internal immutable LINK;
^---------^
'

helpful_scripts.py

`from brownie import (
network,
config,
accounts,
MockV3Aggregator,
VRFCoordinatorMock,
LinkToken,
Contract,
)

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork"]
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-cli"]

def get_account(index=None, id=None):
if index:
return accounts[index]
if id:
return accounts.load(id)
if (
network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS
or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
):
return accounts[0]
return accounts.add(config["wallets"]["from_key"])

contract_to_mock = {
"eth_usd_price_feed": MockV3Aggregator,
"vrf_coordinator": VRFCoordinatorMock,
"link_token": LinkToken,
}

def get_contract(contract_name):
"""This function will grab the contact addresses from the brownie config if
defined, otherwise it will deploy a mock version of that contract and return
that mock contract.

    Args:
        contract_name (string)

    Returns:
        brownie.network.contract.ProjectContract: The most recently deployed
        version of this contract.
"""
contract_type = contract_to_mock[contract_name]
if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
    if len(contract_type) <= 0:
        deploy_mocks()
    contract = contract_type[-1]
else:
    contract_address = config["networks"][network.show_active()][contract_name]
    contract = Contract.from_abi(
        contract_type._name, contract_address, contract_type.abi
    )
return contract
DECIMALS = 8
INITIAL_VALUE = 200000000000

def deploy_mocks(decimals=DECIMALS, initial_value=INITIAL_VALUE):
account = get_account()
MockV3Aggregator.deploy(decimals, initial_value, {"from": account})
link_token = LinkToken.deploy({"from": account})
VRFCoordinatorMock.deploy(link_token.address, {"from": account})
print("Mocks deployed!")
`
brownie-config.yaml

'compiler:
solc:
version: 0.6.0
dependencies:

smartcontractkit/chainlink-brownie-contracts@1.1.1
OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
solc:
remappings:
'@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
'@OpenZeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
networks:
default: development
development:
keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
fee: 100000000000000000
rinkeby:
vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
fee: 100000000000000000
verify: True
mainnet-fork:
eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
wallets:
from_key: ${PRIVATE_KEY}
'
deploy_lottery.py

'from scripts.helpful_scripts import get_account, get_contract
from brownie import Lottery, network, config

def deploy_lottery():
account = get_account()
Lottery.deploy(
get_contract("eth_usd_price_feed").address,
get_contract("vrf_coordinator").address,
get_contract("link_token").address,
config["networks"][network.show_active()]["fee"],
config["networks"][network.show_active()]["keyhash"],
{"from": account},
publish_source=config["networks"][network.show_active()].get("verify", False),
)
print("Deployed lottery!")

def main():
deploy_lottery()
'

.env
'export PRIVATE_KEY=
export WEB3_INFURA_PROJECT_ID=
export ETHERSCAN_TOKEN=
'

ultimately I'm trying to test the contract on a development ganache-cli. The problem is the 'immutable' identifier in the VRFConsumerBase.sol source code. I would like to continue the course, and I do not want to redo all the work I've done so far for a third time. Thank you for the guidance!
@PatrickAlphaC

**Comment by JBush511** [comment]
UPDATE: I was able to compile and run it now, all I did was delete the 'LinkToken.sol' and copied it again back onto my contract. I must have messed with it somehow.

**Comment by PatrickAlphaC** [comment]
Nice work!
